@startuml
package "app" {
  class "Main" as app.Main {
    + {static}void main(String[])
  }
  package "test" {
    class "Test" as app.test.Test {
      +void doMethod1()
      +void doMethod2()
    }
  }
}
@enduml
