
plugins {

  id("groovy-gradle-plugin")
}


//==========================================================================
//リポジトリの設定
//==========================================================================


//プロジェクト側で指定するため、必要な共通リポジトリもここに用意する
repositories {
  mavenCentral()
  gradlePluginPortal()


  maven {
    name = "Architectury"
    url = "https://maven.architectury.dev/"
  }

  maven {
    name = "Fabric"
    url = "https://maven.fabricmc.net/"
  }

  maven {
    name = "Quilt"
    url = "https://maven.quiltmc.org/repository/release/"
  }

  maven {
    name = "Forge"
    url = "https://maven.minecraftforge.net/"
  }

  maven {
    name = "NeoForge"
    url = "https://maven.neoforged.net/releases/"
  }

  maven {
    name = "MinecraftLibraries"
    url = "https://libraries.minecraft.net/"
  }

}



dependencies {

  //プラグイン本体のバージョンもカタログで管理する
  implementation(architecturyLibs.architectury.plugin)
  implementation(architecturyLibs.architectury.loom)
  implementation(architecturyLibs.shadow.plugin)

}

sourceSets {
  main {
    groovy {
      srcDirs("src")
    }
  }

}
